apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: event-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-exporter
    spec:
      serviceAccountName: event-exporter
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
      containers:
      - name: event-exporter
        image: opsgenie/kubernetes-event-exporter:0.8
        imagePullPolicy: IfNotPresent
        args:
        - -conf=/data/config.yaml
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            memory: 500Mi
      volumes:
        - name: data
          configMap:
            name: event-exporter
