apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: event-exporter
resources:
- clusterrolebinding.yaml
- serviceaccount.yaml
- deployment.yaml
configMapGenerator:
- files:
  - config/config.yaml
  name: event-exporter
